# Generated by Django 4.1.4 on 2022-12-14 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nom(s) du chauffeur')),
                ('prenom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prénom(s) du chauffeur')),
                ('date_naissance', models.DateField(blank=True, max_length=100, null=True, verbose_name='Date de naissance')),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de telephone')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresse')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nom(s) du Client')),
                ('prenom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prénom(s) du Client')),
                ('date_naissance', models.DateField(blank=True, max_length=100, null=True, verbose_name='Date de naissance')),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de telephone')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_personne', models.CharField(blank=True, max_length=50, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nom(s) du Livreur')),
                ('prenom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prénom(s) du Livreur')),
                ('date_naissance', models.DateField(blank=True, max_length=100, null=True, verbose_name='Date de naissance')),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de telephone')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nom(s)')),
                ('type', models.IntegerField(choices=[(0, 'PERSONNE_PHYSIQUE'), (1, 'PERSONNE_MORALE')])),
                ('prenom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prénom(s)')),
                ('date_naissance', models.DateField(blank=True, max_length=100, null=True, verbose_name='Date de naissance')),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de telephone')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresse')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Toyota'), (1, 'V8')])),
                ('capacite', models.IntegerField(blank=True, null=True)),
                ('nombre_places', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_vehicules/')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLivreurClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('date_transaction', models.DateTimeField(auto_now=True)),
                ('lieu', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.client')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.livreur')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionChauffeurClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('date_transaction', models.DateTimeField(auto_now=True)),
                ('lieu', models.CharField(blank=True, max_length=50, null=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.chauffeur')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.client')),
            ],
        ),
        migrations.AddField(
            model_name='livreur',
            name='clients',
            field=models.ManyToManyField(through='web.TransactionLivreurClient', to='web.client'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='chauffeur',
            field=models.ManyToManyField(through='web.TransactionChauffeurClient', to='web.chauffeur'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.vehicule'),
        ),
    ]
