# Generated by Django 4.1.4 on 2022-12-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='piece_jointe',
            field=models.FileField(default=None, upload_to='pieces_jointes/livreurs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='piece_jointe',
            field=models.FileField(default=None, upload_to='pieces_jointes/chauffeurs/'),
            preserve_default=False,
        ),
    ]
