# Generated by Django 4.1.4 on 2022-12-07 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nom(s) du chauffeur')),
                ('prenom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prénom(s) du chauffeur')),
                ('date_naissance', models.DateField(blank=True, max_length=100, null=True, verbose_name='Date de naissance')),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de telephone')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresse')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nom(s) du Client')),
                ('prenom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prénom(s) du Client')),
                ('date_naissance', models.DateField(blank=True, max_length=100, null=True, verbose_name='Date de naissance')),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de telephone')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresse')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('chauffeur', models.ManyToManyField(to='web.chauffeur')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_personne', models.CharField(blank=True, max_length=50, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nom(s) du Livreur')),
                ('prenom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prénom(s) du Livreur')),
                ('date_naissance', models.DateField(blank=True, max_length=100, null=True, verbose_name='Date de naissance')),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de telephone')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresse')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('client', models.ManyToManyField(to='web.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nom(s)')),
                ('type', models.CharField(choices=[(0, 'PERSONNE_PHYSIQUE'), (1, 'PERSONNE_MORALE')], max_length=50)),
                ('prenom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prénom(s)')),
                ('date_naissance', models.DateField(blank=True, max_length=100, null=True, verbose_name='Date de naissance')),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de telephone')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresse')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(0, 'Toyota'), (1, 'V8')], max_length=50)),
                ('capacite', models.IntegerField(blank=True, null=True)),
                ('nombre_places', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='user',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.DeleteModel(
            name='Professeur',
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.vehicule'),
        ),
    ]
