# Generated by Django 4.1.4 on 2022-12-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_chauffeur_client_commentaire_livreur_partenaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='chauffeur',
            field=models.ManyToManyField(blank=True, null=True, to='web.chauffeur'),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, to='web.client'),
        ),
    ]
