# Generated by Django 4.1.4 on 2022-12-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_client_chauffeur_alter_livreur_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chauffeur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='email',
        ),
        migrations.AlterField(
            model_name='client',
            name='chauffeur',
            field=models.ManyToManyField(to='web.chauffeur'),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='client',
            field=models.ManyToManyField(to='web.client'),
        ),
    ]
