# Generated by Django 4.1.4 on 2022-12-17 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_chauffeur_geolocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chauffeur',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='geolocalisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.map'),
        ),
    ]
