# Generated by Django 4.1.4 on 2022-12-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_client_geolocalisation_livreur_geolocalisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chauffeur',
            name='geolocalisation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='geolocalisation',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='geolocalisation',
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
