# Generated by Django 4.1.4 on 2022-12-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_chauffeur_geolocalisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='chauffeur',
        ),
        migrations.AddField(
            model_name='client',
            name='chauffeurs',
            field=models.ManyToManyField(through='web.TransactionChauffeurClient', to='web.chauffeur'),
        ),
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
