PERSONNE_PHYSIQUE = 0
PERSONNE_MORALE = 1

PERSONNES_TYPES_VALUES = {'PERSONNE_PHYSIQUE' : PERSONNE_PHYSIQUE,'PERSONNE_MORALE' : PERSONNE_MORALE}

PERSONNES = [
        (PERSONNE_PHYSIQUE, 'PERSONNE_PHYSIQUE'),
        (PERSONNE_MORALE, 'PERSONNE_MORALE'),
        ]